### ISSUE TITLE
У выпадающих кнопок нет соответствующего обозначения

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#17]
В личных сообщениях и в профиле у кнопок с выпадающим списком нет обозначения, что они выпадающие из-за этого посетители не могут найти отправленныу сообщения и т.д.
Нужно к кнопке добавить <span class="caret"></span>

![screenshot_1](https://user-images.githubusercontent.com/2302730/29485737-7b695cbc-84df-11e7-8bb8-8ae9dd6230d9.jpg)

**Comment by zikkuratvk** [comment]
дубль решено
