### ISSUE TITLE
4 цвета кнопок привести к 2 или 3. Кнопки написать сделать самыми яркими

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#18]
![-v0w2b-fs2qbwepcjhwx0q 1](https://user-images.githubusercontent.com/2302730/29485773-6321125c-84e0-11e7-8f66-e1ee8700c0bc.jpeg)

**Comment by zikkuratvk** [comment]
fb2ed602989d58147e5ec1c1bd52a78c1a3c5a38 сделано
