### ISSUE TITLE
В мобильном виде в теме пропадают кнопки пагинации

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#19]
Невозможно перейти на следующую/предыдущую страницу темы
![screenshot_2](https://user-images.githubusercontent.com/2302730/29485792-b2e741d0-84e0-11e7-891a-67fe8f97b764.jpg)

**Comment by zikkuratvk** [comment]
Решено уже b8a5356bc82024cf05ee4a3779785debf651e551
