### ISSUE TITLE
Опция в профиле "Не показывать аватары других пользователей не скрывает аватары

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#23]
Возможно ли сделать так, чтобы аватар полностью скрывался, а не выводился знак вопроса
![screenshot_7](https://user-images.githubusercontent.com/2302730/29485941-0118fd3c-84e4-11e7-952e-d10a9fa13f9e.jpg)

Опция включается здесь:
![screenshot_6](https://user-images.githubusercontent.com/2302730/29485946-0fec99ea-84e4-11e7-959e-885686483e76.jpg)

**Comment by zikkuratvk** [comment]
Решено
