### ISSUE TITLE
В мобильной версии у формы ответа и быстрого ответа большие отступы

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#24]
Неэффективно расходуется свободное место, снижает удобство ответа на темы, т.к. текстовое поле прилично уменьшается и длинные предложения будет сложно писать.
![screenshot_8](https://user-images.githubusercontent.com/2302730/29486011-0b95f44e-84e5-11e7-9074-5aa124e7166d.jpg)

**Comment by zikkuratvk** [comment]
решено
