### ISSUE TITLE
Карма как в личных сообщениях

### ISSUE THREAD

**Issue by Septdir** [zikkuratvk/joomlaforum#28]
Может сделать +/- в инфо блоке как личных сообщениях?
![alt text](https://joomlaforum.ru/index.php?action=dlattach;topic=341110.0;attach=453037868;image "+/-")

**Comment by Omny** [comment]
Это лишняя строка. И так информация о пользователе занимает слишком много места.
![screenshot_2](https://user-images.githubusercontent.com/2302730/29487235-c83edce6-84fe-11e7-8125-37a8dca7260e.jpg)

**Comment by Septdir** [comment]
Да не так уж и много. Зато видно. + можно убрать текст под аватаром Хотя можно и просто поставить справа от кармы так даже лучше

**Comment by zikkuratvk** [comment]
Много... я во постоянно думаю как бы сократить, но пока не получается. Так что карму пока трогать не будем.
