### ISSUE TITLE
Убрать "Просмотреть все непрочитанные темы"

### ISSUE THREAD

**Issue by Septdir** [zikkuratvk/joomlaforum#32]
Честно даже хз возможно ли это. Но данная функция немного раздражает. ИМХО удобнее сразу смотреть Все непрочитанные темы.

**Comment by b2z** [comment]
Имеешь ввиду в action=unreadreplies, когда "Нет непрочитанных тем", сразу показвать все непрочитанные темы?

**Comment by Septdir** [comment]
Ну в идеале, я бы убрать вовсе. И все выводил все непрочитанные. А не часть, которая отбирается по времени.  А что касается изменений то просто ссылку в кнопках поменять да и все.

**Comment by zikkuratvk** [comment]
Не вижу смысла менять механизм существующий, есть лента последних сообщений... внизу... если уж так надо.

**Comment by Septdir** [comment]
Ну смысл то прост. Вот к примеру иногда бывает день на форуме пропускаешь и все постов не видно, нажал сделать все прочитанные и все пост остался без ответа. Такое иногда бывает. 
Ну моё дело маленькое, предложить
