### ISSUE TITLE
"Кирпичи" в топку

### ISSUE THREAD

**Issue by seoelle** [zikkuratvk/joomlaforum#34]
Вернуть как раньше, более информативно; выделить профиль модераторов, админов (может разукрасить? синим/красным)
![screenshot_4](https://user-images.githubusercontent.com/31176597/29493185-612ff728-859a-11e7-918a-494a6cd3b533.png)

**Comment by zikkuratvk** [comment]
Согласен, что надо заменить, заменим.

**Comment by zikkuratvk** [comment]
Сделано
