### ISSUE TITLE
Стили для объединения юзербара и поста - все в белый фон

### ISSUE THREAD

**Issue by Taatshi** [zikkuratvk/joomlaforum#35]
`.body_message .row {
    background: #fff;
}
.poster {
    padding: 10px 0;
}`

Для poster вроде уже что-то было, проверь, можно дописать

**Comment by Septdir** [comment]
Можно еще так. Сделать все белое
`.body_message .row {
    background: #fff;
    padding: 10px 0;
}
.body_message {
    padding: 0;
}
#forumposts .post_separator {
    display: block;
    margin: 0 -10px;   
    background-color: #ddd;
}
.poster { padding: 10px 0; }`

**Comment by zikkuratvk** [comment]
объединил
