### ISSUE TITLE
Предлагаю сменить цвет ссылок

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#39]
т.к. сейчас они не отличаются от текста

Код:
```
a:link, a:visited, a.new_win:link, a.new_win:visited, .table_list tbody.content td.info a.subject {
    color: #38579F;
}
```

Результат:
![-epfodcata6_85vxd25zgg](https://user-images.githubusercontent.com/2302730/29496182-2853c9ac-85d6-11e7-8609-78a3e6313772.jpeg)

![bxo54rahr5eylqr1jxccrw](https://user-images.githubusercontent.com/2302730/29496183-2950ed44-85d6-11e7-97a9-51600514498f.jpeg)

Цвет выбран сочитающийся с шапкой сайта на основе https://color.adobe.com/ru/create/color-wheel/?base=2&rule=Monochromatic&selected=1&name=%D0%9C%D0%BE%D1%8F%20%D1%82%D0%B5%D0%BC%D0%B0%20Color&mode=hsv&rgbvalues=0.5518627450980392,0.642829131652708,0.8490196078431373,0.2184640522875817,0.34266373215959445,0.6241830065359477,0.3568627450980392,0.41568627450980394,0.5490196078431373,0.29715686274509806,0.4660944377751971,0.8490196078431373,0.22686274509803914,0.26425770308125174,0.3490196078431372&swatchOrder=0,1,2,3,4

**Comment by zikkuratvk** [comment]
Сделано но в только для самих постов.
