### ISSUE TITLE
Прикрепленные темы

### ISSUE THREAD

**Issue by seoelle** [zikkuratvk/joomlaforum#42]
Нужно в теме вверху где-то обозначить, что данная тема прикреплена. 
Сейчас, если заходишь в тему, напр. по ссылке, не очевидно, что тема закреплена в разделе, пока не промотаешь вниз, где есть кнопка "открепить тему".

Возможно, стоит продублировать модераторские кнопки вверху, либо добавить иконку в заголовке темы, которая бы обозначала, что тема прикрепленная.

![screenshot_5](https://user-images.githubusercontent.com/31176597/29553307-55c38794-8723-11e7-9f67-990b52a9ec9e.png)
Можно даже наверно для всех тем просто вывести иконки из первой колонки
![uoyajridqsi7wtghqrmzow](https://user-images.githubusercontent.com/31176597/29553384-a702e4d8-8723-11e7-8699-55fa26bc1226.png)

**Comment by zikkuratvk** [comment]
добавил https://s.mail.ru/N2Hx/itVrgC2x1
