### ISSUE TITLE
Формирование урл

### ISSUE THREAD

**Issue by seoelle** [zikkuratvk/joomlaforum#43]
В поисковиках урл вида https://joomlaforum.ru/index.php?topic=310449.30
На форуме формируется - https://joomlaforum.ru/index.php/topic,310449.0.html

**Comment by zikkuratvk** [comment]
Процесс слейки идет уже давно достаточно... до прошлого года было вообще по ровну... страниц то есть каждая страница два урл имела, сейчас есть каноникал и склейка потихоньку идет на последний вариант, ссылок вида https://joomlaforum.ru/index.php?topic=310449.30 осталось относительно не много.

**Comment by seoelle** [comment]
А. А мне казалось наоборот делали - с запятой старый вариант, с = новый. Но раз так, то ок.
