### ISSUE TITLE
Заголовок в теме дважды повторяется

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#51]
Первый раз H1, второй раз то-же самое в H2. Это неправильно с точки зрения структуры документа и занимает лишнее место.

![screenshot_2](https://user-images.githubusercontent.com/2302730/29603231-02e7d2f4-87ec-11e7-9a0b-35f933c54b3d.jpg)

Возможно повтор в H2 стоит убрать, т.к. в категориях и на главной такого повтора нет

**Comment by zikkuratvk** [comment]
Решено
