### ISSUE TITLE
Скобки в пагинации на некоторых страницах

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#54]
Например в списке пользователей, в профиле - просмотр сообщений, в новые сообщения, в новые ответы, в последние сообщения на форуме
![nflfis9yqumuy5-zqq_ajg](https://user-images.githubusercontent.com/2302730/29605474-ab331e9e-87f3-11e7-8af4-58b2c031f1af.jpeg)

**Comment by zikkuratvk** [comment]
Решено
