### ISSUE TITLE
Отдельная кнопка просмотр профиля дублирует нажатие на аватар или на ник

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#55]
Думаю, если есть проблема награмождения иконок и съедания ими лишнего места, то от неё можно отказаться.

![jjwv3im8rjs9blipcog7ka](https://user-images.githubusercontent.com/2302730/29605738-af2a22a8-87f4-11e7-8813-775d2a2fcb0d.jpeg)

**Comment by zikkuratvk** [comment]
Решено
