### ISSUE TITLE
Хлебные крошки в мобильной версии

### ISSUE THREAD

**Issue by seoelle** [zikkuratvk/joomlaforum#56]
js:
```
if ($(window).width() < 700){
if($('.topic_table').length){
    $('.breadcrumb li:eq(-2)').css('display','inline-block');
}
if($('#forumposts').length){
    $('.breadcrumb li:eq(-2), .breadcrumb li:eq(-3)').css('display','inline-block');
}
}
```
*если мы в разделе - один уровень
*если мы в теме - два уровня

~index.css?fin30:4476
удалить:
```
@media (max-width: 700px)
#header .breadcrumb {
    /* display: none; */
}
```
добавить
```
@media (max-width: 700px){
#header ol.breadcrumb li {
    display: none;
}
}
```
![screenshot_7](https://user-images.githubusercontent.com/31176597/29612789-b3b22f48-880b-11e7-805e-13c661ae80ae.png)
![screenshot_8](https://user-images.githubusercontent.com/31176597/29612803-be2a2818-880b-11e7-8d8f-fd8541a376ea.png)

**Comment by zikkuratvk** [comment]
Чего то не получилось внедрить сделал пока свою версию

**Comment by seoelle** [comment]
js куда-нибудь вставил?
можно в https://joomlaforum.ru/Themes/Redsy/scripts/redsy.js?fin25  после
 $(document).ready(function(){

**Comment by seoelle** [comment]
а, смотрю контейнера #forumposts уже нет, раньше все посты темы были в него завернуты, удалил?

можно тогда .body_message прописать, он вроде только в темах есть

**Comment by zikkuratvk** [comment]
Усе нашел свою ошибку, сделали.
