### ISSUE TITLE
Убрать круглоуглы у спойлера

### ISSUE THREAD

**Issue by AlexDaSoul** [zikkuratvk/joomlaforum#57]
Они там вообще не в тему - все квадратное

**Comment by zikkuratvk** [comment]
Вроде все круглое 
https://s.mail.ru/26De/ms1YuvX8W

Или для оценки круглости ты только внутреннюю часть контента используешь?

**Comment by seoelle** [comment]
Слишком кругло, сразу в глаза бросается, можно сделать также закругление 4px вместо 7px, будет лучше)

**Comment by AlexDaSoul** [comment]
На таком масштабе даже 4пх будет выглядеть не очень. Или кругли тогда цитаты тоже. И будем ждать автобус времени - возвращаемся назад на 10 лет по дизайну))

**Comment by zikkuratvk** [comment]
Сделал так... скругление небольшое оставил в 2px.. https://s.mail.ru/79HB/izJpjXLTZ плюс обводку потоньше сделал
