### ISSUE TITLE
код не прокручивается по горизонтали

### ISSUE THREAD

**Issue by Taatshi** [zikkuratvk/joomlaforum#59]
`.block_code pre code {
    overflow-x: scroll;
}`

**Comment by zikkuratvk** [comment]
Добавил правда не нашел где это проверить

**Comment by Taatshi** [comment]
У меня вот тут косяк возник https://joomlaforum.ru/index.php/topic,341209.msg1724442.html#msg1724442

Только что-то не то получилась.  Горизонтальная прокрутка уходит вниз при прокручивании по вертикали.
https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css  для .hljs overflow-x: auto; убрать надо. В общем, посмотри сам.

**Comment by zikkuratvk** [comment]
Переопределил... теперь вроде норм.
