### ISSUE TITLE
Логотип

### ISSUE THREAD

**Issue by seoelle** [zikkuratvk/joomlaforum#61]
Со стилями сам справишься)
https://cdn.joomla.org/images/Joomla_logo.png

![screenshot_10](https://user-images.githubusercontent.com/31176597/29678034-c7644918-8905-11e7-83e6-8b9dfcc04c26.png)

**Comment by zikkuratvk** [comment]
Шустрый уже неделю как обещал логотип :-)

**Comment by seoelle** [comment]
да родной норм будет, разве нет?

**Comment by zikkuratvk** [comment]
сделал
