### ISSUE TITLE
Нужна кнопка цитаты всего сообщения

### ISSUE THREAD

**Issue by AlexDaSoul** [zikkuratvk/joomlaforum#67]
А не только выделенного. Вообще что за странная идея убрать полную цитату, но вставить цитату выделенного? Последнее тоже может быть полезным, но как-то неявно.

**Comment by seoelle** [comment]
если не выделять ничего, то процитируется всё сообщение

**Comment by AlexDaSoul** [comment]
Об этом нигде не написано и это поведение не явно. Если все так, то тогда надо убирать уточнение в скобках про выделенную часть, делать тултипс с пояснением, что можно выделить только часть. Сейчас это выглядит, как можно процмтировать только выделенный текст.

**Comment by zikkuratvk** [comment]
я просто не представляю, куда его воткнуть... а дублировать кнопки как-то не хочется.

**Comment by AlexDaSoul** [comment]
Дап нафик, просто убрать пояснение в скобках, чтобы не вводило в заблуждение и перенести его в title. Все равно ж будешь выносить это из выпадашки наружу?

**Comment by zikkuratvk** [comment]
сделал
