### ISSUE TITLE
Кнопка "Действия"

### ISSUE THREAD

**Issue by AlexDaSoul** [zikkuratvk/joomlaforum#68]
Может ну ее в пим? Не нужно прятать actions под какой-то дропдаун - это классическая ошибка юзабилити. 

Предлагаю убрать дропдаун, расположить экшенсы в строчку там же и заменить слова на иконки. Для пояснения вынести текст в тултипс. 

Это будет +5 к удобству

**Comment by zikkuratvk** [comment]
ты про сообщения??
да я тоже над этим думал особенно для обычных пользователей это не понятно.... в целом я думаю можно как то 4 кнопки расположить нормально там)

**Comment by AlexDaSoul** [comment]
Угу, про них. Там вполне все это влезет и без выпадашек

**Comment by zikkuratvk** [comment]
Ну для супорт тима только плохо влазит... а так норм да...

**Comment by zikkuratvk** [comment]
Сделал
