### ISSUE TITLE
Прибить футер сообщения к низу

### ISSUE THREAD

**Issue by AlexDaSoul** [zikkuratvk/joomlaforum#69]
```
.body_message .col-md-10 {
	display: flex;
	flex-direction: column;
}

.body_message .body_content {
    display: flex;
    flex-direction: column;
    min-height: 100%;
}

.body_message .postarea {
    flex: 1;
}
```

Только для десктопов.

**Comment by AlexDaSoul** [comment]
![2017-08-26_135310](https://user-images.githubusercontent.com/1850022/29740757-807ebd82-8a66-11e7-912d-1e3ae69ff5e0.png)

**Comment by AlexDaSoul** [comment]
это так будет

**Comment by AlexDaSoul** [comment]
![2017-08-26_135526](https://user-images.githubusercontent.com/1850022/29740759-8beaf4ba-8a66-11e7-89c6-e2fcf249775b.png)
это так щас

**Comment by zikkuratvk** [comment]
чего то не работает.

**Comment by AlexDaSoul** [comment]
```
.body_message .row, #personal_messages .body_message.row {
    display: flex;
}
```

**Comment by zikkuratvk** [comment]
6d0d29bdcd8d51efaada5e478c179d16205cabcd
