### ISSUE TITLE
Блок новостей сделать в едином стиле с другими блоками на главной

### ISSUE THREAD

**Issue by Omny** [zikkuratvk/joomlaforum#71]
Предлагаю блок новостей сделать в едином стиле с другими. Добавить ему белый фон и бордюры.
Получится вот так:
![-hpgvx0gsp2zhvjxsg8gnq](https://user-images.githubusercontent.com/2302730/30473316-b36ece6a-9a08-11e7-82ab-8e92eaba6ffe.jpeg)

Нужно заменить в css
#newsfader {
    margin: 0 0 10px 0;
    background: #fff;
    border-left: 1px solid #CCC;
    border-right: 1px solid #CCC;
    border-bottom: 1px solid #CCC;
    border-radius: 4px 4px 0 0;
}

**Comment by zikkuratvk** [comment]
сделал
